"""instagram + facebook_pages performance tables

Revision ID: 057fd739a6bc
Revises: d67f40a439a0
Create Date: 2026-09-09 09:30:17.710890
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.models.base

revision: str = '057fd739a6bc'
down_revision: str | None = 'd67f40a439a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_pages_performance',
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_facebook_pages_performance_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_facebook_pages_performance_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facebook_pages_performance')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_facebook_pages_performance_conn_stream_key')
    )
    op.create_index('ix_facebook_pages_performance_conn_stream_date', 'facebook_pages_performance', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_facebook_pages_performance_date'), 'facebook_pages_performance', ['date'], unique=False)
    op.create_index('ix_facebook_pages_performance_org_conn_date', 'facebook_pages_performance', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_facebook_pages_performance_sync_run', 'facebook_pages_performance', ['sync_run_id'], unique=False)
    op.create_table('instagram_insights_performance',
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_instagram_insights_performance_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_instagram_insights_performance_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instagram_insights_performance')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_instagram_insights_performance_conn_stream_key')
    )
    op.create_index('ix_instagram_insights_performance_conn_stream_date', 'instagram_insights_performance', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_instagram_insights_performance_date'), 'instagram_insights_performance', ['date'], unique=False)
    op.create_index('ix_instagram_insights_performance_org_conn_date', 'instagram_insights_performance', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_instagram_insights_performance_sync_run', 'instagram_insights_performance', ['sync_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_instagram_insights_performance_sync_run', table_name='instagram_insights_performance')
    op.drop_index('ix_instagram_insights_performance_org_conn_date', table_name='instagram_insights_performance')
    op.drop_index(op.f('ix_instagram_insights_performance_date'), table_name='instagram_insights_performance')
    op.drop_index('ix_instagram_insights_performance_conn_stream_date', table_name='instagram_insights_performance')
    op.drop_table('instagram_insights_performance')
    op.drop_index('ix_facebook_pages_performance_sync_run', table_name='facebook_pages_performance')
    op.drop_index('ix_facebook_pages_performance_org_conn_date', table_name='facebook_pages_performance')
    op.drop_index(op.f('ix_facebook_pages_performance_date'), table_name='facebook_pages_performance')
    op.drop_index('ix_facebook_pages_performance_conn_stream_date', table_name='facebook_pages_performance')
    op.drop_table('facebook_pages_performance')
    # ### end Alembic commands ###
