"""leadsquared leads and activities tables

Revision ID: 0cb508e4e171
Revises: 057fd739a6bc
Create Date: 2026-09-11 13:49:38.145661
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.models.base

revision: str = '0cb508e4e171'
down_revision: str | None = '057fd739a6bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leadsquared_activities',
    sa.Column('prospect_activity_id', sa.String(length=64), nullable=False),
    sa.Column('related_prospect_id', sa.String(length=64), nullable=True),
    sa.Column('booking_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_leadsquared_activities_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leadsquared_activities_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leadsquared_activities')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_leadsquared_activities_conn_stream_key')
    )
    op.create_index('ix_leadsquared_activities_booking_id', 'leadsquared_activities', ['booking_id'], unique=False)
    op.create_index('ix_leadsquared_activities_conn_stream_date', 'leadsquared_activities', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_leadsquared_activities_date'), 'leadsquared_activities', ['date'], unique=False)
    op.create_index('ix_leadsquared_activities_org_conn_date', 'leadsquared_activities', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_leadsquared_activities_prospect_activity', 'leadsquared_activities', ['prospect_activity_id'], unique=False)
    op.create_index('ix_leadsquared_activities_related_prospect', 'leadsquared_activities', ['related_prospect_id'], unique=False)
    op.create_index('ix_leadsquared_activities_sync_run', 'leadsquared_activities', ['sync_run_id'], unique=False)
    op.create_table('leadsquared_leads',
    sa.Column('prospect_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_leadsquared_leads_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leadsquared_leads_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leadsquared_leads')),
    sa.UniqueConstraint('connection_id', 'prospect_id', name='uq_leadsquared_leads_conn_prospect'),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_leadsquared_leads_conn_stream_key')
    )
    op.create_index('ix_leadsquared_leads_conn_stream_date', 'leadsquared_leads', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_leadsquared_leads_date'), 'leadsquared_leads', ['date'], unique=False)
    op.create_index('ix_leadsquared_leads_org_conn_date', 'leadsquared_leads', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_leadsquared_leads_prospect', 'leadsquared_leads', ['prospect_id'], unique=False)
    op.create_index('ix_leadsquared_leads_source', 'leadsquared_leads', ['connection_id', 'source'], unique=False)
    op.create_index('ix_leadsquared_leads_sync_run', 'leadsquared_leads', ['sync_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leadsquared_leads_sync_run', table_name='leadsquared_leads')
    op.drop_index('ix_leadsquared_leads_source', table_name='leadsquared_leads')
    op.drop_index('ix_leadsquared_leads_prospect', table_name='leadsquared_leads')
    op.drop_index('ix_leadsquared_leads_org_conn_date', table_name='leadsquared_leads')
    op.drop_index(op.f('ix_leadsquared_leads_date'), table_name='leadsquared_leads')
    op.drop_index('ix_leadsquared_leads_conn_stream_date', table_name='leadsquared_leads')
    op.drop_table('leadsquared_leads')
    op.drop_index('ix_leadsquared_activities_sync_run', table_name='leadsquared_activities')
    op.drop_index('ix_leadsquared_activities_related_prospect', table_name='leadsquared_activities')
    op.drop_index('ix_leadsquared_activities_prospect_activity', table_name='leadsquared_activities')
    op.drop_index('ix_leadsquared_activities_org_conn_date', table_name='leadsquared_activities')
    op.drop_index(op.f('ix_leadsquared_activities_date'), table_name='leadsquared_activities')
    op.drop_index('ix_leadsquared_activities_conn_stream_date', table_name='leadsquared_activities')
    op.drop_index('ix_leadsquared_activities_booking_id', table_name='leadsquared_activities')
    op.drop_table('leadsquared_activities')
    # ### end Alembic commands ###
