"""promote GA4 engagement measures to columns

Revision ID: 8699d8e7aaf9
Revises: aa02ae10359e
Create Date: 2026-09-02 15:20:46.292020
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "8699d8e7aaf9"
down_revision: str | None = "aa02ae10359e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_BACKFILL = {
    "event_count": "eventCount",
    "engagement_rate": "engagementRate",
    "bounce_rate": "bounceRate",
    "avg_session_duration": "averageSessionDuration",
    "screen_page_views_per_session": "screenPageViewsPerSession",
    "user_engagement_duration": "userEngagementDuration",
}


def upgrade() -> None:
    op.add_column("report_rows", sa.Column("event_count", sa.Integer(), nullable=True))
    op.add_column(
        "report_rows", sa.Column("engagement_rate", sa.Numeric(precision=12, scale=6), nullable=True)
    )
    op.add_column("report_rows", sa.Column("bounce_rate", sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column(
        "report_rows", sa.Column("avg_session_duration", sa.Numeric(precision=14, scale=4), nullable=True)
    )
    op.add_column(
        "report_rows",
        sa.Column("screen_page_views_per_session", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "report_rows", sa.Column("user_engagement_duration", sa.Numeric(precision=16, scale=2), nullable=True)
    )

    # Backfill the new columns from values already sitting in the `metrics` JSON
    # (rows synced before this migration). GA4 is the only producer of these.
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    for column, json_key in _BACKFILL.items():
        if is_sqlite:
            expr = f"json_extract(metrics, '$.{json_key}')"
            guard = f"{expr} IS NOT NULL"
        else:
            expr = f"(metrics ->> '{json_key}')::numeric"
            guard = f"metrics ? '{json_key}'"
        op.execute(
            f"UPDATE report_rows SET {column} = {expr} "  # noqa: S608 - keys are a fixed literal map
            f"WHERE connector_id = 'google_analytics' AND {guard}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_rows", "user_engagement_duration")
    op.drop_column("report_rows", "screen_page_views_per_session")
    op.drop_column("report_rows", "avg_session_duration")
    op.drop_column("report_rows", "bounce_rate")
    op.drop_column("report_rows", "engagement_rate")
    op.drop_column("report_rows", "event_count")
    # ### end Alembic commands ###
