"""initial schema

Revision ID: aa02ae10359e
Revises:
Create Date: 2026-08-30 20:49:32.826568
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "aa02ae10359e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)

    op.create_table(
        "api_tokens",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_api_tokens_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
    )
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_tokens_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_tokens_token_hash"), ["token_hash"], unique=True)

    op.create_table(
        "oauth_identities",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_account_id", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("access_token_encrypted", sa.Text(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_oauth_identities_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_identities")),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "external_account_id",
            name="uq_oauth_identities_org_provider_account",
        ),
    )
    with op.batch_alter_table("oauth_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_identities_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "oauth_states",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("connector_id", sa.String(length=80), nullable=True),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("redirect_after", sa.String(length=500), nullable=True),
        sa.Column("identity_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_oauth_states_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_states")),
    )
    with op.batch_alter_table("oauth_states", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_states_state"), ["state"], unique=True)

    op.create_table(
        "connections",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("oauth_identity_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("connector_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("resource_id", sa.String(length=200), nullable=False),
        sa.Column("resource_name", sa.String(length=300), nullable=True),
        sa.Column(
            "resource_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "streams",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("backfill_start_date", sa.Date(), nullable=True),
        sa.Column("lookback_days", sa.Integer(), nullable=False),
        sa.Column("schedule_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("last_error_code", sa.String(length=60), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_records_synced", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["oauth_identity_id"],
            ["oauth_identities.id"],
            name=op.f("fk_connections_oauth_identity_id_oauth_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_connections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
        sa.UniqueConstraint(
            "organization_id", "connector_id", "resource_id", name="uq_connections_org_connector_resource"
        ),
    )
    with op.batch_alter_table("connections", schema=None) as batch_op:
        batch_op.create_index("ix_connections_due", ["enabled", "next_run_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_connections_oauth_identity_id"), ["oauth_identity_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_connections_organization_id"), ["organization_id"], unique=False)

    op.create_table(
        "connector_resources",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("oauth_identity_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("connector_id", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("resource_type", sa.String(length=60), nullable=True),
        sa.Column("parent_id", sa.String(length=200), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("selectable", sa.Boolean(), nullable=False),
        sa.Column("unsupported_reason", sa.Text(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["oauth_identity_id"],
            ["oauth_identities.id"],
            name=op.f("fk_connector_resources_oauth_identity_id_oauth_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_connector_resources_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_resources")),
        sa.UniqueConstraint(
            "oauth_identity_id",
            "connector_id",
            "resource_id",
            name="uq_connector_resources_identity_connector_resource",
        ),
    )
    with op.batch_alter_table("connector_resources", schema=None) as batch_op:
        batch_op.create_index(
            "ix_connector_resources_org_connector", ["organization_id", "connector_id"], unique=False
        )

    op.create_table(
        "ad_entities",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("connection_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("connector_id", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.String(length=200), nullable=False),
        sa.Column("level", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("parent_external_id", sa.String(length=120), nullable=True),
        sa.Column("channel", sa.String(length=60), nullable=True),
        sa.Column("objective", sa.String(length=80), nullable=True),
        sa.Column("daily_budget", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("lifetime_budget", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "raw", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=True
        ),
        sa.Column("sync_run_id", sa.Integer(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_ad_entities_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ad_entities_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_entities")),
        sa.UniqueConstraint(
            "connection_id", "level", "external_id", name="uq_ad_entities_connection_level_id"
        ),
    )
    with op.batch_alter_table("ad_entities", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ad_entities_org_provider_level", ["organization_id", "provider", "level"], unique=False
        )

    op.create_table(
        "report_rows",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("connection_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("connector_id", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("stream", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.String(length=200), nullable=False),
        sa.Column("record_key", sa.String(length=40), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column(
            "dimensions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "raw", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=True
        ),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("conversions", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("conversion_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("revenue", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sessions", sa.Integer(), nullable=True),
        sa.Column("users", sa.Integer(), nullable=True),
        sa.Column("new_users", sa.Integer(), nullable=True),
        sa.Column("page_views", sa.Integer(), nullable=True),
        sa.Column("engaged_sessions", sa.Integer(), nullable=True),
        sa.Column("reach", sa.Integer(), nullable=True),
        sa.Column("average_position", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("sync_run_id", sa.Integer(), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_report_rows_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_report_rows_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_rows")),
        sa.UniqueConstraint(
            "connection_id", "stream", "record_key", name="uq_report_rows_connection_stream_key"
        ),
    )
    with op.batch_alter_table("report_rows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_report_rows_connection_stream_date", ["connection_id", "stream", "date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_report_rows_date"), ["date"], unique=False)
        batch_op.create_index(
            "ix_report_rows_org_connector_date", ["organization_id", "connector_id", "date"], unique=False
        )
        batch_op.create_index("ix_report_rows_sync_run", ["sync_run_id"], unique=False)

    op.create_table(
        "skipped_records",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("connection_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("sync_run_id", sa.Integer(), nullable=True),
        sa.Column("stream", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_skipped_records_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_skipped_records_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skipped_records")),
    )
    with op.batch_alter_table("skipped_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skipped_records_connection_id"), ["connection_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_skipped_records_sync_run_id"), ["sync_run_id"], unique=False)

    op.create_table(
        "source_schemas",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("connection_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stream", sa.String(length=120), nullable=False),
        sa.Column(
            "json_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "last_drift",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_source_schemas_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_schemas")),
        sa.UniqueConstraint("connection_id", "stream", name="uq_source_schemas_connection_stream"),
    )
    with op.batch_alter_table("source_schemas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_schemas_connection_id"), ["connection_id"], unique=False)

    op.create_table(
        "sync_runs",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("connection_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("sync_mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("phase", sa.String(length=40), nullable=True),
        sa.Column("phase_detail", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("api_calls", sa.Integer(), nullable=False),
        sa.Column("slices_completed", sa.Integer(), nullable=False),
        sa.Column("slices_total", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("will_retry", sa.Boolean(), nullable=False),
        sa.Column(
            "state_before",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "state_after",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_sync_runs_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sync_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_runs_connection_id"), ["connection_id"], unique=False)
        batch_op.create_index(
            "ix_sync_runs_connection_started", ["connection_id", "started_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sync_runs_organization_id"), ["organization_id"], unique=False)

    op.create_table(
        "sync_state",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("connection_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stream", sa.String(length=120), nullable=False),
        sa.Column("cursor_field", sa.String(length=120), nullable=True),
        sa.Column("cursor_value", sa.String(length=120), nullable=True),
        sa.Column(
            "state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("records_synced", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_sync_state_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_state")),
        sa.UniqueConstraint("connection_id", "stream", name="uq_sync_state_connection_stream"),
    )
    with op.batch_alter_table("sync_state", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_state_connection_id"), ["connection_id"], unique=False)

    op.create_table(
        "sync_errors",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("sync_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("connection_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stream", sa.String(length=120), nullable=True),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("connector_id", sa.String(length=80), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("recoverable", sa.Boolean(), nullable=False),
        sa.Column("user_action", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_sync_errors_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sync_errors_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_sync_errors_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_errors")),
    )
    with op.batch_alter_table("sync_errors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_errors_connection_id"), ["connection_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sync_errors_sync_run_id"), ["sync_run_id"], unique=False)

    op.create_table(
        "sync_stream_stats",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("sync_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stream", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sync_mode", sa.String(length=20), nullable=False),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("api_calls", sa.Integer(), nullable=False),
        sa.Column("slices_completed", sa.Integer(), nullable=False),
        sa.Column("slices_total", sa.Integer(), nullable=False),
        sa.Column("cursor_value", sa.String(length=120), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_sync_stream_stats_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_stream_stats")),
        sa.UniqueConstraint("sync_run_id", "stream", name="uq_sync_stream_stats_run_stream"),
    )
    with op.batch_alter_table("sync_stream_stats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_stream_stats_sync_run_id"), ["sync_run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_stream_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_stream_stats_sync_run_id"))

    op.drop_table("sync_stream_stats")
    with op.batch_alter_table("sync_errors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_errors_sync_run_id"))
        batch_op.drop_index(batch_op.f("ix_sync_errors_connection_id"))

    op.drop_table("sync_errors")
    with op.batch_alter_table("sync_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_state_connection_id"))

    op.drop_table("sync_state")
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_runs_organization_id"))
        batch_op.drop_index("ix_sync_runs_connection_started")
        batch_op.drop_index(batch_op.f("ix_sync_runs_connection_id"))

    op.drop_table("sync_runs")
    with op.batch_alter_table("source_schemas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_schemas_connection_id"))

    op.drop_table("source_schemas")
    with op.batch_alter_table("skipped_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skipped_records_sync_run_id"))
        batch_op.drop_index(batch_op.f("ix_skipped_records_connection_id"))

    op.drop_table("skipped_records")
    with op.batch_alter_table("report_rows", schema=None) as batch_op:
        batch_op.drop_index("ix_report_rows_sync_run")
        batch_op.drop_index("ix_report_rows_org_connector_date")
        batch_op.drop_index(batch_op.f("ix_report_rows_date"))
        batch_op.drop_index("ix_report_rows_connection_stream_date")

    op.drop_table("report_rows")
    with op.batch_alter_table("ad_entities", schema=None) as batch_op:
        batch_op.drop_index("ix_ad_entities_org_provider_level")

    op.drop_table("ad_entities")
    with op.batch_alter_table("connector_resources", schema=None) as batch_op:
        batch_op.drop_index("ix_connector_resources_org_connector")

    op.drop_table("connector_resources")
    with op.batch_alter_table("connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connections_organization_id"))
        batch_op.drop_index(batch_op.f("ix_connections_oauth_identity_id"))
        batch_op.drop_index("ix_connections_due")

    op.drop_table("connections")
    with op.batch_alter_table("oauth_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_states_state"))

    op.drop_table("oauth_states")
    with op.batch_alter_table("oauth_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_identities_organization_id"))

    op.drop_table("oauth_identities")
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_api_tokens_organization_id"))

    op.drop_table("api_tokens")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))

    op.drop_table("organizations")
    # ### end Alembic commands ###
