"""split_tables

Revision ID: d67f40a439a0
Revises: 8699d8e7aaf9
Create Date: 2026-09-09 01:14:09.736849
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import app.models.base

revision: str = 'd67f40a439a0'
down_revision: str | None = '8699d8e7aaf9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_ads_performance',
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('conversion_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_google_ads_performance_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_google_ads_performance_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_ads_performance')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_google_ads_performance_conn_stream_key')
    )
    op.create_index('ix_google_ads_performance_conn_stream_date', 'google_ads_performance', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_google_ads_performance_date'), 'google_ads_performance', ['date'], unique=False)
    op.create_index('ix_google_ads_performance_org_conn_date', 'google_ads_performance', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_google_ads_performance_sync_run', 'google_ads_performance', ['sync_run_id'], unique=False)
    op.create_table('google_analytics_performance',
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('new_users', sa.Integer(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('engaged_sessions', sa.Integer(), nullable=True),
    sa.Column('bounce_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('engagement_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('avg_session_duration', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('screen_page_views_per_session', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('user_engagement_duration', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_google_analytics_performance_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_google_analytics_performance_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_analytics_performance')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_google_analytics_performance_conn_stream_key')
    )
    op.create_index('ix_google_analytics_performance_conn_stream_date', 'google_analytics_performance', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_google_analytics_performance_date'), 'google_analytics_performance', ['date'], unique=False)
    op.create_index('ix_google_analytics_performance_org_conn_date', 'google_analytics_performance', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_google_analytics_performance_sync_run', 'google_analytics_performance', ['sync_run_id'], unique=False)
    op.create_table('google_search_console_performance',
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('average_position', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_google_search_console_performance_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_google_search_console_performance_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_search_console_performance')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_google_search_console_performance_conn_stream_key')
    )
    op.create_index('ix_google_search_console_performance_conn_stream_date', 'google_search_console_performance', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_google_search_console_performance_date'), 'google_search_console_performance', ['date'], unique=False)
    op.create_index('ix_google_search_console_performance_org_conn_date', 'google_search_console_performance', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_google_search_console_performance_sync_run', 'google_search_console_performance', ['sync_run_id'], unique=False)
    op.create_table('meta_ads_performance',
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('conversion_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('record_key', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_meta_ads_performance_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_meta_ads_performance_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_ads_performance')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name='uq_meta_ads_performance_conn_stream_key')
    )
    op.create_index('ix_meta_ads_performance_conn_stream_date', 'meta_ads_performance', ['connection_id', 'stream', 'date'], unique=False)
    op.create_index(op.f('ix_meta_ads_performance_date'), 'meta_ads_performance', ['date'], unique=False)
    op.create_index('ix_meta_ads_performance_org_conn_date', 'meta_ads_performance', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index('ix_meta_ads_performance_sync_run', 'meta_ads_performance', ['sync_run_id'], unique=False)
    op.drop_index(op.f('ix_report_rows_connection_stream_date'), table_name='report_rows')
    op.drop_index(op.f('ix_report_rows_date'), table_name='report_rows')
    op.drop_index(op.f('ix_report_rows_org_connector_date'), table_name='report_rows')
    op.drop_index(op.f('ix_report_rows_sync_run'), table_name='report_rows')
    op.execute('DROP TABLE report_rows CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_rows',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('connector_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('stream', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('record_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('conversions', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('conversion_value', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engaged_sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_position', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('schema_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sync_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_rate', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True),
    sa.Column('bounce_rate', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True),
    sa.Column('avg_session_duration', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('screen_page_views_per_session', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('user_engagement_duration', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_report_rows_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_report_rows_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_rows')),
    sa.UniqueConstraint('connection_id', 'stream', 'record_key', name=op.f('uq_report_rows_connection_stream_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_report_rows_sync_run'), 'report_rows', ['sync_run_id'], unique=False)
    op.create_index(op.f('ix_report_rows_org_connector_date'), 'report_rows', ['organization_id', 'connector_id', 'date'], unique=False)
    op.create_index(op.f('ix_report_rows_date'), 'report_rows', ['date'], unique=False)
    op.create_index(op.f('ix_report_rows_connection_stream_date'), 'report_rows', ['connection_id', 'stream', 'date'], unique=False)
    op.drop_index('ix_meta_ads_performance_sync_run', table_name='meta_ads_performance')
    op.drop_index('ix_meta_ads_performance_org_conn_date', table_name='meta_ads_performance')
    op.drop_index(op.f('ix_meta_ads_performance_date'), table_name='meta_ads_performance')
    op.drop_index('ix_meta_ads_performance_conn_stream_date', table_name='meta_ads_performance')
    op.drop_table('meta_ads_performance')
    op.drop_index('ix_google_search_console_performance_sync_run', table_name='google_search_console_performance')
    op.drop_index('ix_google_search_console_performance_org_conn_date', table_name='google_search_console_performance')
    op.drop_index(op.f('ix_google_search_console_performance_date'), table_name='google_search_console_performance')
    op.drop_index('ix_google_search_console_performance_conn_stream_date', table_name='google_search_console_performance')
    op.drop_table('google_search_console_performance')
    op.drop_index('ix_google_analytics_performance_sync_run', table_name='google_analytics_performance')
    op.drop_index('ix_google_analytics_performance_org_conn_date', table_name='google_analytics_performance')
    op.drop_index(op.f('ix_google_analytics_performance_date'), table_name='google_analytics_performance')
    op.drop_index('ix_google_analytics_performance_conn_stream_date', table_name='google_analytics_performance')
    op.drop_table('google_analytics_performance')
    op.drop_index('ix_google_ads_performance_sync_run', table_name='google_ads_performance')
    op.drop_index('ix_google_ads_performance_org_conn_date', table_name='google_ads_performance')
    op.drop_index(op.f('ix_google_ads_performance_date'), table_name='google_ads_performance')
    op.drop_index('ix_google_ads_performance_conn_stream_date', table_name='google_ads_performance')
    op.drop_table('google_ads_performance')
    # ### end Alembic commands ###
